import { Platform, StyleSheet } from "react-native";

import { adaptiveColor as adaptive } from "./adaptive-color";

export const colors = {
  background: adaptive("#F3F4F7", "#000000"),
  surface: adaptive("#FFFFFF", "#1C1C1E"),
  inset: adaptive("#F5F6F8", "#242426"),
  text: adaptive("#18212F", "#F2F2F7"),
  secondary: adaptive("#586274", "#AEAEB2"),
  tertiary: adaptive("#697386", "#8E8E93"),
  separator: adaptive("#DFE3EA", "#38383A"),
  fill: adaptive("#E9ECF1", "#2C2C2E"),
  blue: adaptive("#1765CC", "#0A84FF"),
  blueSoft: adaptive("#EAF1FC", "#102A43"),
  bluePressed: adaptive("#D8E6FA", "#17395C"),
  green: adaptive("#24734D", "#30D158"),
  greenSoft: adaptive("#EAF5EF", "#16351F"),
  orange: adaptive("#A55016", "#FF9F0A"),
  orangeSoft: adaptive("#FCF0E7", "#3A2915"),
  pink: adaptive("#C33759", "#FF375F"),
  pinkSoft: adaptive("#FBECEF", "#3A1722"),
  purple: adaptive("#7351BA", "#BF5AF2"),
  purpleSoft: adaptive("#F1ECFA", "#2D2040"),
  teal: adaptive("#14767D", "#64D2FF"),
  tealSoft: adaptive("#E8F4F4", "#153437"),
  danger: adaptive("#B52B35", "#FF453A"),
  dangerSoft: adaptive("#FBECEF", "#3A1715"),
  onAccent: "#FFFFFF",
  scrim: adaptive("rgba(18, 25, 38, 0.42)", "rgba(0, 0, 0, 0.68)"),
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  page: 20,
  xl: 24,
  section: 28,
  xxl: 32,
} as const;
export const radii = {
  small: 8,
  control: 10,
  card: 16,
  sheet: 24,
  pill: 999,
} as const;
export const motion = {
  press: 110,
  selection: 180,
  content: 240,
  progress: 360,
} as const;
export const typography = StyleSheet.create({
  largeTitle: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 41,
    fontWeight: "700",
    letterSpacing: -1.1,
  },
  title: {
    color: colors.text,
    fontSize: 28,
    lineHeight: 35,
    fontWeight: "700",
    letterSpacing: -0.7,
  },
  section: {
    color: colors.text,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "700",
    letterSpacing: -0.35,
  },
  headline: {
    color: colors.text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  body: { color: colors.text, fontSize: 17, lineHeight: 24 },
  label: {
    color: colors.secondary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
  },
  caption: { color: colors.secondary, fontSize: 13, lineHeight: 18 },
  footnote: { color: colors.tertiary, fontSize: 12, lineHeight: 17 },
  metric: {
    color: colors.text,
    fontSize: 32,
    lineHeight: 39,
    fontWeight: "600",
    letterSpacing: -1,
    fontVariant: ["tabular-nums"],
  },
});

export const surfaces = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    borderCurve: "continuous",
    borderWidth: 0,
  },
  title: {
    ...typography.largeTitle,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.separator,
    borderRadius: radii.control,
    borderWidth: 1,
    color: colors.text,
    fontSize: 17,
    fontFamily: Platform.select({
      ios: "System",
      web: "system-ui",
      default: "sans-serif",
    }),
    fontWeight: "400",
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blue,
    borderRadius: radii.control,
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonText: {
    color: colors.onAccent,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "600",
    textAlign: "center",
  },
  secondaryButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blueSoft,
    borderRadius: radii.control,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryText: {
    color: colors.blue,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "600",
    textAlign: "center",
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 60,
    padding: 16,
    gap: 12,
  },
  separator: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  backdrop: {
    alignItems: "center",
    backgroundColor: colors.scrim,
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  dialog: {
    backgroundColor: colors.surface,
    borderRadius: radii.sheet,
    borderCurve: "continuous",
    maxWidth: 420,
    padding: 24,
    width: "100%",
  },
  sheetHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.separator,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    minHeight: 56,
    paddingHorizontal: 16,
  },
});
