import { Platform, StyleSheet } from "react-native";

export const colors = {
  background: "#F3F4F7",
  surface: "#FFFFFF",
  inset: "#F5F6F8",
  text: "#18212F",
  secondary: "#586274",
  tertiary: "#697386",
  separator: "#DFE3EA",
  fill: "#E9ECF1",
  blue: "#1765CC",
  blueSoft: "#EAF1FC",
  bluePressed: "#D8E6FA",
  green: "#24734D",
  greenSoft: "#EAF5EF",
  orange: "#A55016",
  orangeSoft: "#FCF0E7",
  pink: "#C33759",
  pinkSoft: "#FBECEF",
  purple: "#7351BA",
  purpleSoft: "#F1ECFA",
  teal: "#14767D",
  tealSoft: "#E8F4F4",
  danger: "#B52B35",
  dangerSoft: "#FBECEF",
  onAccent: "#FFFFFF",
  scrim: "rgba(18, 25, 38, 0.42)",
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  page: 20,
  xl: 24,
  section: 28,
  xxl: 32,
} as const;
export const radii = {
  small: 8,
  control: 10,
  card: 16,
  sheet: 24,
  pill: 999,
} as const;
export const motion = {
  press: 110,
  selection: 180,
  content: 240,
  progress: 360,
} as const;
export const typography = StyleSheet.create({
  largeTitle: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 41,
    fontWeight: "700",
    letterSpacing: -1.1,
  },
  title: {
    color: colors.text,
    fontSize: 28,
    lineHeight: 35,
    fontWeight: "700",
    letterSpacing: -0.7,
  },
  section: {
    color: colors.text,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "700",
    letterSpacing: -0.35,
  },
  headline: {
    color: colors.text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  body: { color: colors.text, fontSize: 17, lineHeight: 24 },
  label: {
    color: colors.secondary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
  },
  caption: { color: colors.secondary, fontSize: 13, lineHeight: 18 },
  footnote: { color: colors.tertiary, fontSize: 12, lineHeight: 17 },
  metric: {
    color: colors.text,
    fontSize: 32,
    lineHeight: 39,
    fontWeight: "600",
    letterSpacing: -1,
    fontVariant: ["tabular-nums"],
  },
});

export const surfaces = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.card,
    borderCurve: "continuous",
    borderWidth: 0,
  },
  title: {
    ...typography.largeTitle,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.separator,
    borderRadius: radii.control,
    borderWidth: 1,
    color: colors.text,
    fontSize: 17,
    fontFamily: Platform.select({
      ios: "System",
      web: "system-ui",
      default: "sans-serif",
    }),
    fontWeight: "400",
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blue,
    borderRadius: radii.control,
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonText: {
    color: colors.onAccent,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "600",
    textAlign: "center",
  },
  secondaryButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blueSoft,
    borderRadius: radii.control,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryText: {
    color: colors.blue,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "600",
    textAlign: "center",
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 60,
    padding: 16,
    gap: 12,
  },
  separator: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  backdrop: {
    alignItems: "center",
    backgroundColor: colors.scrim,
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  dialog: {
    backgroundColor: colors.surface,
    borderRadius: radii.sheet,
    borderCurve: "continuous",
    maxWidth: 420,
    padding: 24,
    width: "100%",
  },
  sheetHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.separator,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    minHeight: 56,
    paddingHorizontal: 16,
  },
});
