import { Platform, StyleSheet } from "react-native";
import { colors, surfaces } from "./theme";

export const trackingStyles = StyleSheet.create({
  page: { backgroundColor: colors.background, flexGrow: 1, padding: 20 },
  title: { ...surfaces.title, marginBottom: 20 },
  section: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "600",
    marginBottom: 8,
  },
  label: {
    color: colors.secondary,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.separator,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.text,
    fontSize: 17,
    fontFamily: Platform.select({
      ios: "System",
      web: "system-ui",
      default: "sans-serif",
    }),
    fontWeight: "400",
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  card: { ...surfaces.card, borderRadius: 22, padding: 16 },
  chip: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.fill,
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  chipActive: { backgroundColor: colors.blue },
  chipText: { color: colors.secondary, fontSize: 14, fontWeight: "600" },
  chipTextActive: { color: colors.surface, fontSize: 14, fontWeight: "600" },
  button: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blue,
    borderRadius: 13,
    minHeight: 54,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonText: { color: colors.surface, fontSize: 16, fontWeight: "600" },
  addButton: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
    backgroundColor: colors.blueSoft,
    borderRadius: 12,
    minHeight: 48,
    padding: 12,
    marginBottom: 20,
  },
  addButtonText: { color: colors.blue, fontSize: 15, fontWeight: "600" },
  listAddButton: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    backgroundColor: "#0064D6",
    borderRadius: 13,
    minHeight: 54,
    padding: 14,
    marginBottom: 20,
  },
  listAddButtonText: { color: colors.surface, fontSize: 16, fontWeight: "600" },
  success: {
    color: colors.green,
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 12,
  },
  error: { color: "#B42318", fontSize: 14, lineHeight: 20, marginBottom: 12 },
});
