import { StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, Line, Polyline } from 'react-native-svg';

import { latestSample, pointsForRange, trendRangeBounds, type TimestampPoint, type TrendRange, type VitalKind, type VitalSample, unitFor } from '../../domain/vitals';

type Series = { points: TimestampPoint[]; color: string };
function average(points: TimestampPoint[]): number | undefined { return points.length ? points.reduce((sum, point) => sum + point.value, 0) / points.length : undefined; }
function coordinates(points: TimestampPoint[], allValues: number[], start: Date, end: Date) { const width = 300; const height = 94; const pad = 10; const min = Math.min(...allValues); const max = Math.max(...allValues); const span = Math.max(max - min, 1); const elapsed = Math.max(end.getTime() - start.getTime(), 1); return points.map((point) => ({ x: pad + Math.max(0, Math.min(1, (new Date(point.at).getTime() - start.getTime()) / elapsed)) * (width - pad * 2), y: height - pad - ((point.value - min) / span) * (height - pad * 2) })); }
function LinePlot({ series, color, allValues, start, end }: { series: TimestampPoint[]; color: string; allValues: number[]; start: Date; end: Date }) { const points = coordinates(series, allValues, start, end); const path = points.map((point) => `${point.x},${point.y}`).join(' '); return <>{points.length > 1 ? <Polyline points={path} fill="none" stroke={color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /> : null}{points.map((point) => <Circle key={`${point.x}-${point.y}`} cx={point.x} cy={point.y} r="3.5" fill={color} />)}</>; }
function axisLabels(range: TrendRange, start: Date, end: Date): [string, string, string] { if (range === 'D') return ['12 AM', '12 PM', '11:59 PM']; const date = (value: Date) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(value); const middle = new Date((start.getTime() + end.getTime()) / 2); return [date(start), date(middle), date(end)]; }
function Chart({ series, range }: { series: Series[]; range: TrendRange }) { const values = series.flatMap((item) => item.points.map((point) => point.value)); const { start, end } = trendRangeBounds(range); if (!values.length) return <Text style={styles.empty}>Add a reading to begin this trend.</Text>; const labels = axisLabels(range, start, end); return <View><Svg width="100%" height="114" viewBox="0 0 300 94"><Line x1="10" y1="84" x2="290" y2="84" stroke="#D9E2EC" strokeWidth="1" />{series.map((item, index) => <LinePlot key={index} series={item.points} color={item.color} allValues={values} start={start} end={end} />)}</Svg><View style={styles.axis}><Text style={styles.axisText}>{labels[0]}</Text><Text style={styles.axisText}>{labels[1]}</Text><Text style={styles.axisText}>{labels[2]}</Text></View></View>; }
function rangeName(range: TrendRange): string { return range === 'D' ? 'Daily' : range === 'W' ? 'Weekly' : range === 'M' ? 'Monthly' : range === '6M' ? '6-month' : 'Yearly'; }

export function TrendCard({ title, kind, samples, range }: { title: string; kind: VitalKind; samples: VitalSample[]; range: TrendRange }) { const points = pointsForRange(samples, kind, range); const latest = latestSample(samples, kind); const mean = average(points); return <View style={styles.card}><View style={styles.header}><Text style={styles.title}>{title}</Text><Text style={styles.value}>{latest ? `${latest.value} ${unitFor(kind)}` : 'No data'}</Text></View><Text style={styles.subtitle}>{rangeName(range)} average: {mean ? `${mean.toFixed(1)} ${unitFor(kind)}` : '--'}</Text><Chart series={[{ points, color: '#16776A' }]} range={range} /></View>; }
export function BloodPressureTrendCard({ samples, range }: { samples: VitalSample[]; range: TrendRange }) { const systolic = pointsForRange(samples, 'systolic_bp', range); const diastolic = pointsForRange(samples, 'diastolic_bp', range); const sysAverage = average(systolic); const diaAverage = average(diastolic); return <View style={styles.card}><View style={styles.header}><Text style={styles.title}>Blood pressure</Text><Text style={styles.value}>{sysAverage && diaAverage ? `${Math.round(sysAverage)}/${Math.round(diaAverage)}` : 'No data'}</Text></View><Text style={styles.subtitle}>{rangeName(range)} average - mmHg</Text><View style={styles.legend}><View style={[styles.legendDot, { backgroundColor: '#16776A' }]} /><Text style={styles.legendText}>Systolic</Text><View style={[styles.legendDot, { backgroundColor: '#3B82C4' }]} /><Text style={styles.legendText}>Diastolic</Text></View><Chart series={[{ points: systolic, color: '#16776A' }, { points: diastolic, color: '#3B82C4' }]} range={range} /></View>; }
const styles = StyleSheet.create({ card: { backgroundColor: '#FFFFFF', borderColor: '#E6EEF3', borderWidth: 1, borderRadius: 16, marginBottom: 14, padding: 16 }, header: { alignItems: 'baseline', flexDirection: 'row', justifyContent: 'space-between' }, title: { color: '#243B53', fontSize: 16, fontWeight: '800' }, value: { color: '#16776A', fontSize: 19, fontWeight: '800' }, subtitle: { color: '#7B8794', fontSize: 13, marginTop: 4 }, legend: { alignItems: 'center', flexDirection: 'row', gap: 5, marginTop: 12 }, legendDot: { borderRadius: 5, height: 9, marginLeft: 6, width: 9 }, legendText: { color: '#627D98', fontSize: 12 }, empty: { color: '#7B8794', fontSize: 14, marginTop: 22 }, axis: { flexDirection: 'row', justifyContent: 'space-between', marginTop: -13 }, axisText: { color: '#7B8794', fontSize: 10 } });
