import { useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { useAuth } from '../../src/features/auth/auth-provider';
import { getFoodSuggestions, saveFood, type FoodInput, type FoodSuggestion } from '../../src/features/training/repository';

const meals: Exclude<FoodInput['mealType'], 'meal'>[] = ['breakfast', 'lunch', 'dinner', 'snack'];
export default function NutritionScreen() {
  const { session } = useAuth(); const [foodName, setFoodName] = useState(''); const [calories, setCalories] = useState(''); const [protein, setProtein] = useState(''); const [mealType, setMealType] = useState<FoodInput['mealType']>(); const [suggestions, setSuggestions] = useState<FoodSuggestion[]>([]); const [feedback, setFeedback] = useState(''); const [saving, setSaving] = useState(false); const request = useRef(0);
  async function searchSavedFoods(query: string) { if (!session || !query.trim()) { setSuggestions([]); return; } const current = ++request.current; try { const matches = await getFoodSuggestions(session.user.id, query); if (current === request.current) setSuggestions(matches); } catch { if (current === request.current) setSuggestions([]); } }
  function chooseFood(item: FoodSuggestion) { setFoodName(item.name); setCalories(String(item.calories)); setProtein(String(item.proteinGrams)); setSuggestions([]); }
  async function save() { if (!session) return setFeedback('Please sign in before saving.'); const cal = Number(calories); const grams = Number(protein); if (!foodName.trim() || !mealType || !Number.isInteger(cal) || cal < 0 || !Number.isFinite(grams) || grams < 0) return setFeedback('Enter a food, calories, protein, and meal type.'); setSaving(true); setFeedback(''); try { await saveFood(session.user.id, { foodName, mealType, calories: cal, proteinGrams: grams }); setFoodName(''); setCalories(''); setProtein(''); setMealType(undefined); setSuggestions([]); setFeedback('Food entry saved. It will be suggested next time you search for it.'); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Could not save food.'); } finally { setSaving(false); } }
  return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Food</Text><Text style={styles.copy}>Log your own foods and nutrition. Saved foods appear as you type; nothing is preloaded.</Text><Text style={styles.label}>Food</Text><TextInput placeholder="Search your saved foods or enter a new food" placeholderTextColor="#9FB3C8" style={styles.input} value={foodName} onChangeText={(value) => { setFoodName(value); void searchSavedFoods(value); }} />{suggestions.map((item) => <Pressable key={item.name} onPress={() => chooseFood(item)} style={styles.suggestion}><Text style={styles.suggestionName}>{item.name}</Text><Text style={styles.suggestionMeta}>{item.calories} cal / {item.proteinGrams}g protein</Text></Pressable>)}<View style={styles.row}><Field label="Calories" value={calories} onChangeText={setCalories} /><Field label="Protein (g)" value={protein} onChangeText={setProtein} /></View><Text style={styles.label}>Meal</Text><View style={styles.chips}>{meals.map((meal) => <Pressable key={meal} onPress={() => setMealType(meal)} style={[styles.chip, mealType === meal && styles.chipActive]}><Text style={mealType === meal ? styles.chipTextActive : styles.chipText}>{meal}</Text></Pressable>)}</View>{feedback ? <Text style={feedback.includes('saved') ? styles.success : styles.error}>{feedback}</Text> : null}<Pressable disabled={saving} onPress={() => void save()} style={styles.button}><Text style={styles.buttonText}>{saving ? 'Saving...' : 'Save food'}</Text></Pressable></ScrollView>;
}
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput keyboardType="decimal-pad" placeholder="0" placeholderTextColor="#9FB3C8" style={styles.input} value={value} onChangeText={onChangeText} /></View>; }
const styles = StyleSheet.create({ page: { backgroundColor: '#F7FAFC', flexGrow: 1, padding: 20 }, title: { color: '#102A43', fontSize: 30, fontWeight: '800' }, copy: { color: '#627D98', lineHeight: 21, marginBottom: 20, marginTop: 7 }, label: { color: '#486581', fontSize: 14, fontWeight: '800', marginBottom: 8 }, input: { backgroundColor: '#fff', borderColor: '#D9E2EC', borderWidth: 1, borderRadius: 12, color: '#102A43', fontSize: 16, marginBottom: 14, padding: 13 }, suggestion: { backgroundColor: '#fff', borderBottomColor: '#E6EEF3', borderBottomWidth: 1, paddingHorizontal: 11, paddingVertical: 10 }, suggestionName: { color: '#243B53', fontWeight: '800' }, suggestionMeta: { color: '#627D98', fontSize: 13, marginTop: 3 }, row: { flexDirection: 'row', gap: 12 }, field: { flex: 1 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, chip: { backgroundColor: '#E6EEF3', borderRadius: 20, paddingHorizontal: 13, paddingVertical: 9 }, chipActive: { backgroundColor: '#16776A' }, chipText: { color: '#486581', fontWeight: '700', textTransform: 'capitalize' }, chipTextActive: { color: '#fff', fontWeight: '800', textTransform: 'capitalize' }, success: { color: '#16776A', fontWeight: '700', marginBottom: 10 }, error: { color: '#B42318', marginBottom: 10 }, button: { alignItems: 'center', backgroundColor: '#16776A', borderRadius: 13, minHeight: 54, justifyContent: 'center' }, buttonText: { color: '#fff', fontSize: 16, fontWeight: '800' } });
