import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { type VitalSample, unitFor } from '../../src/domain/vitals';
import { useAuth } from '../../src/features/auth/auth-provider';
import { createId } from '../../src/features/vitals/storage';
import { queueLocalVitals, syncVitals } from '../../src/features/vitals/sync';

export default function HealthLogScreen() {
  const { session, configured } = useAuth(); const [weight, setWeight] = useState(''); const [systolic, setSystolic] = useState(''); const [diastolic, setDiastolic] = useState(''); const [pulse, setPulse] = useState(''); const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState('');
  async function save() { if (!session) return setFeedback('Please sign in before saving.'); const measurements = [['weight', weight], ['systolic_bp', systolic], ['diastolic_bp', diastolic], ['pulse', pulse]] as const; const supplied = measurements.filter(([, value]) => value.trim()); if (!supplied.length || supplied.some(([, value]) => !Number.isFinite(Number(value)) || Number(value) <= 0)) return setFeedback('Enter at least one positive number.'); if ((systolic && !diastolic) || (!systolic && diastolic)) return setFeedback('Enter both systolic and diastolic readings.'); const now = new Date().toISOString(); const correlationId = systolic ? createId() : undefined; const samples: VitalSample[] = supplied.map(([kind, value]) => ({ id: createId(), userId: session.user.id, kind, value: Number(value), unit: unitFor(kind), occurredAt: now, correlationId, source: 'manual', createdAt: now })); setSaving(true); setFeedback(''); try { await queueLocalVitals(samples); const result = configured ? await syncVitals(session.user.id) : undefined; setWeight(''); setSystolic(''); setDiastolic(''); setPulse(''); setFeedback(result?.error ? `Saved on this device. Sync is waiting: ${result.error}` : 'Saved and synced to Supabase.'); } catch (error) { setFeedback(error instanceof Error ? `Could not save: ${error.message}` : 'Could not save this entry.'); } finally { setSaving(false); } }
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Health Log</Text><Text style={styles.copy}>Vitals save locally first, then securely sync to your account.</Text><Text style={styles.section}>Vitals</Text><Field label="Weight (lb)" value={weight} onChangeText={setWeight} /><Text style={styles.section}>Blood pressure (mmHg)</Text><View style={styles.row}><Field label="Systolic" value={systolic} onChangeText={setSystolic} compact /><Field label="Diastolic" value={diastolic} onChangeText={setDiastolic} compact /></View><Field label="Pulse (bpm, optional)" value={pulse} onChangeText={setPulse} />{feedback ? <Text style={feedback.startsWith('Saved') ? styles.success : styles.error}>{feedback}</Text> : null}<Pressable disabled={saving} onPress={() => void save()} style={styles.button}><Text style={styles.buttonText}>{saving ? 'Saving...' : 'Save measurements'}</Text></Pressable></ScrollView>;
}
function Field({ label, value, onChangeText, compact }: { label: string; value: string; onChangeText: (value: string) => void; compact?: boolean }) { return <View style={compact ? styles.compact : undefined}><Text style={styles.label}>{label}</Text><TextInput keyboardType="decimal-pad" placeholder="0" placeholderTextColor="#9FB3C8" style={styles.input} value={value} onChangeText={onChangeText} /></View>; }
const styles = StyleSheet.create({ page: { backgroundColor: '#F7FAFC', flexGrow: 1, padding: 20 }, title: { color: '#102A43', fontSize: 30, fontWeight: '800' }, copy: { color: '#627D98', lineHeight: 21, marginBottom: 14, marginTop: 7 }, section: { color: '#243B53', fontSize: 17, fontWeight: '800', marginBottom: 10, marginTop: 8 }, label: { color: '#486581', fontSize: 14, fontWeight: '600', marginBottom: 7 }, input: { backgroundColor: '#fff', borderColor: '#D9E2EC', borderWidth: 1, borderRadius: 12, color: '#102A43', fontSize: 18, marginBottom: 16, padding: 14 }, row: { flexDirection: 'row', gap: 12 }, compact: { flex: 1 }, success: { color: '#16776A', fontWeight: '700', marginBottom: 8 }, error: { color: '#B42318', marginBottom: 8 }, button: { alignItems: 'center', backgroundColor: '#16776A', borderRadius: 13, marginTop: 8, minHeight: 54, justifyContent: 'center' }, buttonText: { color: '#fff', fontSize: 16, fontWeight: '800' } });
